### ISSUE TITLE
Use position number for expressions in c-3po-lib

### ISSUE THREAD

**Issue by AlexMost** [c-3po-org/c-3po#96]
The global configuration option - `useNumberedExpressions`, that will use position number for expressions in translations instead of variable names. This option will allow using complex expressions inside translations like:

# Option
name - *useNumberedExpressions*
default value - false

# Example
```js
import { useNumberedExpressions } from 'c-3po'
useNumberedExpressions(true);

t`Hello ${ getUserName() }`
```
c-3po will be searching for `Hello ${ 0 }` in the `.po` file in that case.

# Roadmap
- [ ] implement global setting
- [ ] tests for t,jt,gettext,ngettext
- [ ] doc - https://c-3po.js.org/configuration-c-3po-lib.html

> Prerequisite for this issue https://github.com/c-3po-org/c-3po/issues/95

**Comment by AlexMost** [comment]
@tlrobinson hey, I was on a little vacation, now I am back and going to do that to the end of the week.

**Comment by AlexMost** [comment]
Checked the behavior of the library and it seems `0.7.3` works already with indices.
